#!/bin/bash
# Run development environment with two backends and frontend

npx concurrently \
  --names "srv,cl0,cl1" \
  --prefix-colors "blue,green,magenta" \
  "./scripts/run-dev-server" \
  "./scripts/run-dev-client" \
  "SRV_ID=1 ./scripts/run-dev-client"
