#!/bin/bash
# Run development environment with two backends and frontend

npx concurrently \
  --names "clnt,srv0,srv1" \
  --prefix-colors "magenta,green,blue" \
  "./scripts/run-dev-client" \
  "./scripts/run-dev-server" \
  "SRV_ID=1 ./scripts/run-dev-server"
