#!/bin/bash
# Run development environment with backend and frontend

npx concurrently \
  --names "srv,cli" \
  --prefix-colors "green,magenta" \
  "./scripts/run-dev-server" \
  "./scripts/run-dev-client"
